openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  /api/v1/users/sign_in:
    post:
      summary: User Login 
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserLogin'
      responses:
        '201':
          description: Successfully signed in
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginSuccessResponse'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/users:
    get:
      summary: List of all users
      tags:
        - Users
      security:
        - JWT: []
      responses:
        '200':
          description: Users List
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      summary: Registers a new user
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserRegistration'
      responses:
        '201':
          description: Successfully signed up
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/users/{id}:
    get:
      summary: Get user by ID
      tags:
        - Users
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: User details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    patch:
      summary: Update user profile
      tags:
        - Users
      security:
        - JWT: []   
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserUpdate'
      responses:
        '200':
          description: Updated user details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/leads:
    get:
      summary: List of all leads
      tags:
        - Leads
      responses:
        '200':
          description: Leads List
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      summary: Create a new lead
      tags:
        - Leads
      security:
        - JWT: []        
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/LeadInput'
      responses:
        '201':
          description: Lead Successfully Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LeadSuccessResponse'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/leads/{id}:
    get:
      summary: Get lead by ID
      tags:
        - Leads
      security:
        - JWT: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Lead details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LeadInput'

    patch:
      summary: Update lead data
      tags:
        - Leads
      security:
        - JWT: []   
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/LeadInput'
      responses:
        '200':
          description: Updated lead details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LeadInput'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    delete:
      summary: Delete lead by ID
      tags:
        - Leads
      security:
        - JWT: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Delete Lead
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LeadInput'


components:
  securitySchemes:
    JWT:
      type: apiKey
      name: Authorization
      in: header

  schemas:
    UserLogin:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      required:
        - email
        - password

    LoginSuccessResponse:
      type: object
      properties:
        message:
          type: string
        token:
          type: string

    UserUpdate:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        primary_mobile:
          type: string
        secondary_mobile:
          type: string
        linkedin_url:
          type: string
        experience:
          type: integer
        bio:
          type: string
        achievements:
          type: string
        password:
          type: string
          minLength: 6    # Minimum password length
        password_confirmation:
          type: string
                  
    UserRegistration:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
          format: email   # Email format validation
        password:
          type: string
          minLength: 6    # Minimum password length
        password_confirmation:
          type: string
        primary_mobile:
          type: string
        secondary_mobile:
          type: string
        linkedin_url:
          type: string
        experience:
          type: integer
        bio:
          type: string
        achievements:
          type: string
        role:
          type: string
      required:
        - email
        - password
        - password_confirmation

    LeadInput:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        budget:
          type: string

        income:
          type: string
        status:
          type: string
          default: 'published'
      required:
        - title


    SuccessResponse:
      type: object
      properties:
        message:
          type: string


    LeadSuccessResponse:
      type: object
      properties:
        message:
          type: string
        lead:
          type: string


    ErrorResponse:
      type: object
      properties:
        error:
          type: string
    User:
      type: object
      properties:
        id:
          type: integer
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        primary_mobile:
          type: string
        secondary_mobile:
          type: string
        linkedin_url:
          type: string
        experience:
          type: integer
        bio:
          type: string
        achievements:
          type: string
